### ISSUE TITLE
move to pd-externals?

### ISSUE THREAD

**Issue by umlaeute** [pd-externals/list-abs#1]
In an attempt to make the git repositories of various (well known and used) Pd-libraries more visible, I created the [pd-externals](https://github.com/pd-externals) group (similar in spirit to the olde puredata SVN).

I'd therefore like to suggest to move this library to the `pd-externals` group.
How does this sound?

**Comment by chr15m** [comment]
Sounds good, although this is actually @footils project. I will move it there anyway.

**Comment by footils** [comment]
Hi,

Chris, it's fine: I'm currently not developing anything in Pd for lack
of time outside of work unfortunatly ... :-(

I trust your good judgement on what's best for list-abs.

All the best,
-- 
Frank

On Fri, Dec 01, 2017 at 12:51:02AM +0000, Chris McCormick wrote:
> Sounds good, although this is actually @footils project. I will move it there anyway.


-- 
 Frank Barknecht                                     _ ______footils.org__
